<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>oden</string>
	</array>
	<key>name</key>
	<string>Oden</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(import|package)\b</string>
			<key>name</key>
			<string>keyword.other.oden</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Control</string>
			<key>match</key>
			<string>\b(let|in|if|then|else|any|fn)\b</string>
			<key>name</key>
			<string>keyword.control.oden</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Types</string>
			<key>match</key>
			<string>\b(int|string|boolean)\b|#\w+</string>
			<key>name</key>
			<string>support.type.oden</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numbers</string>
			<key>match</key>
			<string>(?&lt;!\w)(\b(\d+)|(\d+(\.\d+)?(e[+-]?\d+)?)\b)</string>
			<key>name</key>
			<string>constant.numeric.oden</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Booleans</string>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.oden</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operators</string>
			<key>match</key>
			<string>[+\-*\/?&lt;&gt;=]|\+\+|\:\:|==|&lt;=|&gt;=|-&gt;
</string>
			<key>name</key>
			<string>keyword.operator.oden</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\")</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.oden</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String</string>
			<key>end</key>
			<string>(\")</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.oden</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.oden</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.oden</string>
	<key>uuid</key>
	<string>34e52019-fd43-42bc-ba92-f091830827d4</string>
</dict>
</plist>
